[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dymoval"
version = "0.1"
authors = [
  { name="Ubaldo Tiberi", email="ubaldo.tiberi@volvo.com" },
]
description = "Dymoval is a Python package for validating models and analyzing datasets"
readme = "README.md"
license = { file="LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/VolvoGroup/dymoval"
"Bug Tracker" = "https://github.com/VolvoGroup/dymoval/issues"

[tool.black]
target-version = ['py39']
line-length = 80
exclude = ["scripts", "docs"]

[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
# For now, mypy is only run on ./src
# The following two shall be module specific
ignore_missing_imports = true
disable_error_code = ["name-defined"]

[[tool.mypy.overrides]]
module = [
    "dataset",
    "validation",
    "utils",
    "config",
]




[tool.pytest.ini_options]
norecursedirs = ["scripts"] # Exclude folders
