[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dymoval"
version = "0.1"
authors = [
  { name="Ubaldo Tiberi", email="ubaldo.tiberi@gmail.com" },
]
description = "A small example package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/VolvoGroup/dymoval"
"Bug Tracker" = "https://github.com/VolvoGroup/dymoval/issues"

[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
ignore_missing_imports = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
