{% set name = "dymoval" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dymoval-{{ version }}.tar.gz
  sha256: aca5760d14132d852d4e230178f28218b47fa82d8e1d833c5fda44af1071be3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - pandas
    - matplotlib-base
    - control
    - scipy
    - pathlib
    - numpy
    - tomli
    - h5py

test:
  imports:
    - dymoval
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Dymoval is a Python package for validating models and analyzing datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ubaldot
