{% set name = "dymoval" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dymoval-{{ version }}.tar.gz
  sha256: b3d1ce3f482a23d0848cd78a8063a25834c3e28a50c6841ff58f02cb15d791f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pdm-backend
    - pip
  run:
    - python >=3.10
    - pandas
    - matplotlib-base
    - scipy
    - pathlib
    - numpy
    - tomli
    - h5py

test:
  imports:
    - dymoval
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Dymoval is a Python package for validating models and analyzing datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ubaldot
