# Publish on PyPI and conda-forge

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  pypi_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build package
        run: python -m hatch build
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  conda_publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Publish Loop Conda
          uses: Loop3D/conda-publish-action@1.0
          with:
            subdir: "conda"
            anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
            platforms: "win osx linux"
