# Publish on PyPI and conda-forge

name: Publish

on:
  push:
  #release:
  #  types: [published]
  workflow_dispatch:

jobs:
  pypi_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build package
        run: python -m hatch build
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  conda_publish:
    runs-on: ubuntu-latest
    name: Conda skeleton publish
    steps:
      - name: Publish conda package from PyPI package
        uses: actions/conda-skeleton-publish@v2
        with:
          pypi_package: "dymoval"
          python_version: "3.10"
          upload_channel: "conda-forge"
          access_token: ${{ secrets.ANACONDA_TOKEN }}
          stable: true
